[project]
name = "anarcism"
version = "0.1.0"
description = "Pinned native reference environment for anarcism compatibility generation"
readme = "README.md"
authors = [
    { name = "Moritz Onken", email = "mo@revanta.bio" }
]
requires-python = ">=3.14"
dependencies = [
    "anarci==2026.2.13.2",
]

[project.scripts]
anarcism = "anarcism:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
