[package]
name = "anarcism-python"
description = "Python bindings for anarcism"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "_anarcism"
crate-type = ["cdylib"]

[features]
default = ["extension-module"]
extension-module = ["pyo3/extension-module"]

[dependencies]
anarcism-core = { path = "../anarcism-core" }
pyo3 = { version = "0.27.2", default-features = false, features = [
    "abi3-py311",
    "generate-import-lib",
    "macros",
] }
